spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost/analytics_db"
    username: analytics_service
    password: password
available:
  queries:
    - Java
    - Kotlin
    - Android
    - Javascript
    - React
    - PHP
    - iOS
    - .NET
    - Python
management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health" ]
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
security:
  jwt:
    accessSecret: "qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=="
    refreshSecret: "zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg=="
    accessExpirationInMinutes: 5
    refreshExpirationInMinutes: 43200